### ISSUE TITLE
Option to fail or pass the action based on alerts

### ISSUE THREAD

**Issue by sshniro** [zaproxy/action-baseline#31]
Currently, the action fails if it finds any alerts in the report. This will trigger an email for the failed action. It will be good to make this behavior configurable.

```yaml
  fail_action:
    description: 'Fail or pass the action based on alerts'
    required: false
    default: false
```

**Comment by richAtreides** [comment]
Is this being worked on?

**Comment by kingthorin** [comment]
As a work around you could simply add a step to your action workflow that exits successfully:

```yml
...
steps:
    ...
      - name: Exit with success
        run: exit 0
```
