### ISSUE TITLE
Cannot turn off GitHub issue filing

### ISSUE THREAD

**Issue by AlexDHoffer** [zaproxy/action-baseline#56]
Hi folks,

We are mostly interested in this tool so that we don't have to run the Docker container by hand. But, we don't want this to automatically file issues to our GitHub repo - we are totally satisfied with it just spitting out an artifact that we can stash after scanning.

How can we get to the point with this Action where it doesn't require you to file an Issue to the repo?

**Comment by AlexDHoffer** [comment]
My apologies, I did not see this tucked into the documentation! https://github.com/zaproxy/action-baseline#token

**Comment by AlexDHoffer** [comment]
Re-opening because the documentation did not fix this issue. Setting token as follows:

````
      - name: Run OWASP Action on Dev3
        id: run_owasp
        uses: zaproxy/action-baseline@v0.4.0
        with:
          target: 'https://${{ env.URL_SHORTHAND }}.dev.kollective.app'
          cmd_options: '-r ${{ env.APP_NAME }}-dev-baseline.html'
          token: ""
````

or

````
      - name: Run OWASP Action on Dev3
        id: run_owasp
        uses: zaproxy/action-baseline@v0.4.0
        with:
          target: 'https://${{ env.URL_SHORTHAND }}.dev.kollective.app'
          cmd_options: '-r ${{ env.APP_NAME }}-dev-baseline.html'
          token: ''
````

resulted in: Error: Bad credentials

**Comment by AlexDHoffer** [comment]
Re-opening because the documentation did not fix this issue. Setting token as follows:

````
      - name: Run OWASP Action on Dev3
        id: run_owasp
        uses: zaproxy/action-baseline@v0.4.0
        with:
          target: 'https://${{ env.URL_SHORTHAND }}.dev.kollective.app'
          cmd_options: '-r ${{ env.APP_NAME }}-dev-baseline.html'
          token: ""
````

or

````
      - name: Run OWASP Action on Dev3
        id: run_owasp
        uses: zaproxy/action-baseline@v0.4.0
        with:
          target: 'https://${{ env.URL_SHORTHAND }}.dev.kollective.app'
          cmd_options: '-r ${{ env.APP_NAME }}-dev-baseline.html'
          token: ''
````

resulted in: Error: Bad credentials
